# Generated by Django 4.1.3 on 2022-12-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=40, verbose_name='主机ip')),
                ('cpu_usage', models.FloatField(max_length=20, verbose_name='CPU使用率')),
                ('menory_usage', models.FloatField(max_length=20, verbose_name='内存使用率')),
                ('hardpan_usage', models.FloatField(max_length=20, verbose_name='硬盘使用率')),
                ('network_i', models.FloatField(max_length=40, verbose_name='网络I')),
                ('network_o', models.FloatField(max_length=40, verbose_name='网络O')),
                ('time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='日期时间')),
            ],
        ),
    ]
